# Generated by Django 3.2.12 on 2022-11-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221118_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='naver_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
