# Generated by Django 3.2.12 on 2022-11-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews_image',
            new_name='review_image',
        ),
    ]
