# Generated by Django 3.2.12 on 2022-11-15 04:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_auto_20221115_1338'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='review_comments',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글 수'),
        ),
        migrations.AlterField(
            model_name='review',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack_review', to='snacks.snack'),
        ),
    ]
