# Generated by Django 3.2.12 on 2022-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_comments',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글 수'),
        ),
    ]
