# Generated by Django 3.2.12 on 2022-11-11 02:48

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snack_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
                ('snack_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/snacks/')),
                ('price', models.IntegerField(blank=True)),
                ('stock', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='snacks.snack_category')),
            ],
        ),
    ]
