# Generated by Django 3.2.12 on 2022-11-14 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snacks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('shipping_address', models.CharField(max_length=250)),
                ('register_data', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(default='결제완료', max_length=250)),
                ('contact_number', models.CharField(max_length=250, null=True)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacks.snack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
