# Generated by Django 3.2.12 on 2022-11-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221113_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='주문승인', max_length=250),
        ),
    ]
