# Generated by Django 3.2.12 on 2022-11-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='결제완료', max_length=250),
        ),
    ]
